version: '3'
services:
  flask-be:
    build:
      context: ./real-estate-flask-rest-api
    ports:
      - "5000:5000"
    volumes:
      - ./real-estate-flask-rest-api:/flask-be-api
    env_file:
      - ./real-estate-flask-rest-api/.env  # Include the path to your .env file for Flask backend
    depends_on:
    - postgres

  fe-react:
    build:
      context: ./real-estate-react-app
    ports:
      - "3000:3000"
    depends_on:
      - flask-be
    env_file:
      - ./real-estate-react-app/.env.local  # Include the path to your .env file for React frontend

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
