name: Cypress Tests

on:
  push:
    branches:
      - main  # Adjust this branch name to match your main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: 'Create env files'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.FE_ENV_FILE }}" > ./real-estate-react-app/.env.local
          echo "${{ secrets.BE_ENV_FILE }}" >> ./real-estate-flask-rest-api/.env

      - name: Build and Start Docker Containers
        run: |
          docker-compose up --build -d

      - name: Run Cypress Tests
        run: |
          docker-compose exec -T fe-react node ./e2e-run-tests.js

      - name: Stop and Remove Docker Containers
        run: docker-compose down
