name: Cypress Tests

on:
  push:
    branches:
      - main  # Adjust this branch name to match your main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: 'Create env files'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.BE_ENV_FILE }}" >> ./real-estate-flask-rest-api/.env

      - name: Build and Start Docker Containers
        run: |
          docker-compose up --build -d

      # Add a step to sleep for 30 seconds
      - name: Sleep for 30 seconds
        run: |
          echo "Sleeping for 30 seconds..."
          sleep 30
          echo "Done sleeping."

      - name: Run Cypress Tests
        run: |
          docker-compose exec -T fe-react node ./e2e-run-tests.js

      - name: Show logs on Error
        if: success() || failure()
        run: |
          # Use the Docker Compose logs command to display logs from the backend service
          docker-compose ps
          docker-compose logs flask-be

      - name: Stop and Remove Docker Containers
        run: docker-compose down
